#!/bin/bash

# directories
PLUGINS_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"
UTILS_DIR="$CONFIG_DIR/utils"

# colors
COLOR_PRIMARY=0xff3e6868
BAR_BACKGROUND_COLOR=0x60725a7a
UNFOCUSED_WORKSPACE_COLOR=$COLOR_PRIMARY
FOCUSED_WORKSPACE_COLOR=0xffda620b
FOREGROUND_COLOR=0xffe8d8c9

# blur radius
BLUR_RADIUS=4

# font variables
SKETCHYBAR_APP_FONT="sketchybar-app-font"
HACK_NERD_FONT="Hack Nerd Font"
FONT_WEIGHT_BOLD="Bold"
FONT_WEIGHT_REGULAR="Regular"
DEFAULT_FONT_FAMILY=$HACK_NERD_FONT
APP_ICON_FONT_FAMILY=$SKETCHYBAR_APP_FONT
ICON_FONT_SIZE="16.0"
LABEL_FONT_SIZE="14.0"

# bar variables
BAR_PADDING_INLINE=8
BAR_HEIGHT=40

# item variables
ITEM_BACKGROUND_HEIGHT=24
ITEM_BACKGROUND_CORNER_RADIUS=8
ITEM_BACKGROUND_PADDING_INLINE=4
ITEM_BACKGROUND_COLOR=$COLOR_PRIMARY
ITEM_ICON_PADDING_LEFT=8
ITEM_ICON_PADDING_RIGHT=4
ITEM_ICON_COLOR=$FOREGROUND_COLOR
ITEM_LABEL_PADDING_LEFT=4
ITEM_LABEL_PADDING_RIGHT=8
ITEM_LABEL_PERCENTAGE_DISPLAY_WIDTH=40
ITEM_LABEL_COLOR=$FOREGROUND_COLOR
